### PR TITLE
Sagemake notebook data encryption fix

### PR DESCRIPTION
**Pull request by ajinkya1986**

### CODE REVIEW

**Review by mpurusottamc — APPROVED** [review]
lgtm

**Comment by mpurusottamc** [comment]
@ajinkya1986 can you resolve these conflicts?

**Review by mpurusottamc — APPROVED** [review]
lgtm

**Comment by ajinkya1986** [comment]
Conflicts resolved

**Review by mpurusottamc — APPROVED** [review]
lgtm

**Pull request merged**
